language: java

env:
  - MAVEN_POM_VERSION=

addons:
  sonarcloud:
    organization: "famaridon-github"
    token:
      secure: $SONAR_TOKEN

cache:
  directories:
  - $HOME/.m2

before_install:
  - source ./travis-ci/parse-pom.sh
  - echo MAVEN_POM_VERSION=$MAVEN_POM_VERSION

install: # the build step
   - mvn clean install -B -V

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    draft: true
    file:
    - "jdwp-over-ws-server/target/jdwp-over-ws.war"
    - "jdwp-over-ws-server/target/jdwp-over-ws-$MAVEN_POM_VERSION+thorntail.jar"
    - "jdwp-over-ws-client/target/jdwp-over-ws-client-$MAVEN_POM_VERSION.jar"
    - "jdwp-over-ws-client/target/jdwp-over-ws-client-$MAVEN_POM_VERSION+shade.jar"
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change

