language: java

env:
  - MAVEN_POM_VERSION=

cache:
  directories:
  - $HOME/.m2

before_install:
  - source ./travis-ci/parse-pom.sh
  - echo MAVEN_POM_VERSION=$MAVEN_POM_VERSION

install: # the build step
   - mvn clean install -B -V

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file:
    - "jdwp-over-ws-server/target/tcp-over-ws*.war"
    - "jdwp-over-ws-client/target/jdwp-over-ws-client*.jar"
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    draft: true
    prerelease: true
    name: $MAVEN_POM_VERSION
    tag_name: $MAVEN_POM_VERSION
    file:
    - "jdwp-over-ws-server/target/tcp-over-ws*.war"
    - "jdwp-over-ws-client/target/jdwp-over-ws-client*.jar"
    skip_cleanup: true
    on:
      branch: master
      tags: true


notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change

